name: eslint
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Action ESLint
        uses: sibiraj-s/action-eslint@v1.0.1
